// Golden Hypermarket Pala - Central Database (data.js)
const siteData = {
  categories: [
    {
      id: 'grocery',
      name: 'Grocery & Staples',
      nameMl: 'പലചരക്ക് സാധനങ്ങൾ',
      icon: 'fa-wheat-awn',
      image: 'https://images.unsplash.com/photo-1588964895597-cfccd6e2dbf9?auto=format&fit=crop&w=400&q=80',
      banner: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80',
      description: 'Authentic Kerala Matta rice, premium biryani grains, pure cooking oils, organic pulses, flours and traditional masalas.',
      subcategories: ['Rice & Grains', 'Spices & Masalas', 'Edible Oils & Ghee', 'Flours & Podi', 'Dals & Pulses', 'Sugar & Jaggery']
    },
    {
      id: 'produce',
      name: 'Fresh Vegetables',
      nameMl: 'പച്ചക്കറികൾ',
      icon: 'fa-carrot',
      image: 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=400&q=80',
      banner: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1400&q=80',
      description: 'Daily fresh farm harvest sourced directly from local Pala, Meenachil, and Idukki high range farms every morning at 7 AM.',
      subcategories: ['Local Kerala Veggies', 'High-Range Greens', 'Gourds & Coconuts', 'Roots & Tubers', 'Salad Veggies', 'Organic Greens']
    },
    {
      id: 'fruits',
      name: 'Fresh Fruits',
      nameMl: 'പഴവർഗ്ഗങ്ങൾ',
      icon: 'fa-apple-whole',
      image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=400&q=80',
      banner: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=1400&q=80',
      description: 'Sweet, juicy local Kerala bananas, high range papayas, pineapples, and premium imported seasonal fruits.',
      subcategories: ['Kerala Bananas (Nendran, Robusta)', 'Tropical & Seasonal', 'Citrus & Melons', 'Apples & Pears', 'Exotic Fruits', 'Dry Fruits & Nuts']
    },
    {
      id: 'meat-fish',
      name: 'Meat & Fresh Fish',
      nameMl: 'ഇറച്ചി & മത്സ്യം',
      icon: 'fa-fish',
      image: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=400&q=80',
      banner: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=1400&q=80',
      description: 'Cleaned, cut, and hygienically packed fresh marine fish, freshwater fish, tender chicken cuts, and premium mutton.',
      subcategories: ['Fresh Marine Fish', 'Freshwater Catch', 'Tender Farm Chicken', 'Fresh Mutton Cuts', 'Ready to Cook', 'Marinated Cuts']
    },
    {
      id: 'dairy',
      name: 'Dairy & Eggs',
      nameMl: 'പാൽ & മുട്ട ഉൽപ്പന്നങ്ങൾ',
      icon: 'fa-egg',
      image: 'https://images.unsplash.com/photo-1528750997573-59b89d56f4f7?auto=format&fit=crop&w=400&q=80',
      banner: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=1400&q=80',
      description: 'Pure Malanadu cow ghee, farm fresh milk, curd, unsalted butter, creamy paneer, and nutritious country eggs.',
      subcategories: ['Milk & Curd', 'Pure Desi Ghee', 'Butter & Cheese', 'Fresh Paneer', 'Farm & Country Eggs', 'Flavoured Milk']
    },
    {
      id: 'bakery',
      name: 'Bakery & Snacks',
      nameMl: 'ബേക്കറി & സ്നാക്സ്',
      icon: 'fa-bread-slice',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
      banner: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1400&q=80',
      description: 'Freshly baked breads, traditional Kerala banana chips, rusks, cakes, cookies, and evening tea-time bites.',
      subcategories: ['Fresh Breads & Buns', 'Kerala Crisps & Chips', 'Cakes & Pastries', 'Rusks & Cookies', 'Traditional Sweets', 'Namkeens & Mixtures']
    },
    {
      id: 'household',
      name: 'Household & Cleaning',
      nameMl: 'വീട്ടുപകരണങ്ങൾ & ക്ലീനിംഗ്',
      icon: 'fa-spray-can-sparkles',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=400&q=80',
      banner: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=1400&q=80',
      description: 'Top detergent brands, floor cleaners, dishwash liquids, air fresheners, pooja essentials, and hygiene products.',
      subcategories: ['Detergents & Fabric Care', 'Dishwash & Kitchen Cleaners', 'Floor & Surface Cleaners', 'Paper & Tissues', 'Pooja Needs', 'Insect Repellents']
    },
    {
      id: 'beverages',
      name: 'Beverages & Tea',
      nameMl: 'പാനീയങ്ങൾ & ചായ',
      icon: 'fa-mug-hot',
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=400&q=80',
      banner: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=1400&q=80',
      description: 'Highland dust teas, freshly ground filter coffee, health drink mixes, natural fruit juices, and mineral waters.',
      subcategories: ['Kerala Dust Tea', 'Filter & Instant Coffee', 'Health & Malt Drinks', 'Packaged Juices', 'Syrups & Squashes', 'Bottled Waters']
    },
    {
      id: 'electronics',
      name: 'Electronics & Appliances',
      nameMl: 'ഇലക്ട്രോണിക്സ് & ഉപകരണങ്ങൾ',
      icon: 'fa-blender',
      image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=400&q=80',
      banner: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=1400&q=80',
      description: 'Heavy duty mixer grinders, pressure cookers, electric kettles, induction stoves, iron boxes, and smart accessories.',
      subcategories: ['Mixer Grinders & Blenders', 'Pressure Cookers', 'Electric Kettles & Stoves', 'Fans & Irons', 'Personal Grooming', 'Audio & Accessories']
    },
    {
      id: 'fashion',
      name: 'Fashion & Apparels',
      nameMl: 'വസ്ത്രങ്ങൾ & ഫാഷൻ',
      icon: 'fa-shirt',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=400&q=80',
      banner: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=1400&q=80',
      description: 'Traditional Kerala Kasavu mundu, daily wear cotton sarees, shirts, kidswear, bath towels, and bed linens.',
      subcategories: ['Kerala Traditional Mundu', 'Men Cotton Wear', 'Women Sarees & Kurtis', 'Kidswear & Toys', 'Towels & Bath Linens', 'Footwear & Umbrellas']
    }
  ],

  // Products Database (12+ items per category = 120+ products)
  products: [
    // ----------------- 1. GROCERY & STAPLES (12 Items) -----------------
    {
      id: 1,
      category: 'grocery',
      name: 'Pavizham Jaya Rice Premium Bag',
      nameMl: 'പവിഴം ജയ അരി (10 കി.ഗ്രാം)',
      brand: 'Pavizham',
      weight: '10 kg Pack',
      price: 469,
      oldPrice: 560,
      discount: '16% OFF',
      image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 184,
      stock: 'In Stock',
      description: 'Premium quality sortex cleaned Jaya rice from Pavizham. Perfect for daily meals, soft texture and rich aroma.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 2,
      category: 'grocery',
      name: 'Kera Drops 100% Pure Coconut Oil',
      nameMl: 'കേര ഡ്രോപ്സ് ശുദ്ധമായ വെളിച്ചെണ്ണ',
      brand: 'Kera Drops',
      weight: '1 Litre Bottle',
      price: 219,
      oldPrice: 280,
      discount: '22% OFF',
      image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 210,
      stock: 'In Stock',
      description: 'Extracted from mature sun-dried copra sourced across Kerala farms. 100% natural, unadulterated coconut oil.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 3,
      category: 'grocery',
      name: 'Kitchen Treasures Kashmiri Chilli Powder',
      nameMl: 'കിച്ചൻ ട്രഷേഴ്സ് കാശ്മീരി മുളകുപൊടി',
      brand: 'Kitchen Treasures',
      weight: '500g Pack',
      price: 180,
      oldPrice: 240,
      discount: '25% OFF',
      image: 'https://images.unsplash.com/photo-1607672632458-9eb56696346b?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 95,
      stock: 'In Stock',
      description: 'Gives rich vibrant red color and mild warmth to Kerala fish curries and gravies without excessive heat.',
      isDeal: true,
      isFeatured: false
    },
    {
      id: 4,
      category: 'grocery',
      name: 'Double Horse Roasted White Puttu Podi',
      nameMl: 'ഡബിൾ ഹോഴ്സ് വറുത്ത പുട്ടുപൊടി',
      brand: 'Double Horse',
      weight: '1 kg Pack',
      price: 69,
      oldPrice: 99,
      discount: '30% OFF',
      image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 320,
      stock: 'In Stock',
      description: 'Finely steam-roasted rice flour making the softest traditional Kerala puttu within minutes.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 5,
      category: 'grocery',
      name: 'India Gate Select Basmati Biryani Rice',
      nameMl: 'ഇന്ത്യാ ഗേറ്റ് സെലക്ട് ബിരിയാണി അരി',
      brand: 'India Gate',
      weight: '5 kg Bag',
      price: 499,
      oldPrice: 650,
      discount: '23% OFF',
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 140,
      stock: 'In Stock',
      description: 'Extra long grain aged basmati rice that elongates up to 2.5x after cooking. Ideal for Malabar Dum Biryani.',
      isDeal: true,
      isFeatured: false
    },
    {
      id: 6,
      category: 'grocery',
      name: 'Nirmal Vadi Kerala Matta Rice',
      nameMl: 'നിർമ്മൽ വാടി മട്ട അരി',
      brand: 'Nirmal',
      weight: '5 kg Bag',
      price: 275,
      oldPrice: 340,
      discount: '19% OFF',
      image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 88,
      stock: 'In Stock',
      description: 'Healthy nutrient-dense parboiled red rice from Palakkad paddy fields. High fiber and rich authentic taste.',
      isDeal: false,
      isFeatured: true
    },
    {
      id: 7,
      category: 'grocery',
      name: 'Eastern Coriander / Malli Powder',
      nameMl: 'ഈസ്റ്റേൺ മല്ലിപ്പൊടി (500 ഗ്രാം)',
      brand: 'Eastern',
      weight: '500g Pack',
      price: 115,
      oldPrice: 145,
      discount: '21% OFF',
      image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
      rating: 4.6,
      reviews: 62,
      stock: 'In Stock',
      description: 'Slow roasted aromatic coriander seeds milled into fine powder with zero artificial colors.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 8,
      category: 'grocery',
      name: 'Gold Winner Pure Refined Sunflower Oil',
      nameMl: 'ഗോൾഡ് വിന്നർ സൂര്യകാന്തി എണ്ണ',
      brand: 'Gold Winner',
      weight: '1 Litre Pouch',
      price: 145,
      oldPrice: 185,
      discount: '21% OFF',
      image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 130,
      stock: 'In Stock',
      description: 'Light, non-sticky cooking oil enriched with Vitamins A & D. Low absorption for healthy cooking.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 9,
      category: 'grocery',
      name: 'Peringome Organic Round Jaggery (Sharkkara)',
      nameMl: 'നാടൻ ഉണ്ട ശർക്കര (1 കി.ഗ്രാം)',
      brand: 'Peringome',
      weight: '1 kg Block',
      price: 95,
      oldPrice: 130,
      discount: '27% OFF',
      image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 74,
      stock: 'In Stock',
      description: 'Pure chemical-free unrefined cane jaggery. Ideal for Kerala payasam, unniyappam, and morning tea.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 10,
      category: 'grocery',
      name: 'Brahmins Traditional Sambar Powder',
      nameMl: 'ബ്രാഹ്മിൻസ് സാമ്പാർ പൊടി',
      brand: 'Brahmins',
      weight: '250g Box',
      price: 68,
      oldPrice: 85,
      discount: '20% OFF',
      image: 'https://images.unsplash.com/photo-1607672632458-9eb56696346b?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 155,
      stock: 'In Stock',
      description: 'Authentic Travancore style sambar masala made with hing, fenugreek, dal, and handpicked red chillies.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 11,
      category: 'grocery',
      name: 'Double Horse Appam & Idiyappam Podi',
      nameMl: 'ഡബിൾ ഹോഴ്സ് അപ്പം & ഇടിയപ്പം പൊടി',
      brand: 'Double Horse',
      weight: '1 kg Pack',
      price: 78,
      oldPrice: 105,
      discount: '25% OFF',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 110,
      stock: 'In Stock',
      description: 'Specially milled rice flour formulation for crispy lacy appams and soft melt-in-mouth idiyappams.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 12,
      category: 'grocery',
      name: 'Aashirvaad Superior MP Sharbati Atta',
      nameMl: 'ആശീർവാദ് സമ്പൂർണ്ണ ആട്ട (5 കി.ഗ്രാം)',
      brand: 'Aashirvaad',
      weight: '5 kg Bag',
      price: 260,
      oldPrice: 310,
      discount: '16% OFF',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 240,
      stock: 'In Stock',
      description: '100% whole wheat grains harvested from Madhya Pradesh fields for the softest rotis and chapatis.',
      isDeal: false,
      isFeatured: false
    },

    // ----------------- 2. FRESH VEGETABLES (12 Items) -----------------
    {
      id: 101,
      category: 'produce',
      name: 'Fresh Farm Coconut (നാടൻ നാളികേരം)',
      nameMl: 'നാടൻ തേങ്ങ / നാളികേരം',
      brand: 'Pala Farm Direct',
      weight: 'Per Kg (approx 2-3 pcs)',
      price: 63,
      oldPrice: 75,
      discount: '16% OFF',
      image: 'https://images.unsplash.com/photo-1544378730-8b5104b18790?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 310,
      stock: 'In Stock',
      description: 'Harvested fresh from local Meenachil coconut groves. Rich in natural milk and sweet oil content.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 102,
      category: 'produce',
      name: 'Tender Ash Gourd (നാടൻ കുമ്പളങ്ങ)',
      nameMl: 'നാടൻ കുമ്പളങ്ങ',
      brand: 'Pala Farm Direct',
      weight: 'Per Kg',
      price: 20,
      oldPrice: 32,
      discount: '37% OFF',
      image: 'https://images.unsplash.com/photo-1590779033100-9f60a05a013d?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 120,
      stock: 'In Stock',
      description: 'Cooling, nutrient-packed fresh ash gourd. Ideal for Moru curry, Olan, and refreshing morning detox juice.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 103,
      category: 'produce',
      name: 'Fresh Crisp Salad Cucumber (വെള്ളരി)',
      nameMl: 'സാലഡ് വെള്ളരി',
      brand: 'Vagamon Farms',
      weight: 'Per Kg',
      price: 35,
      oldPrice: 48,
      discount: '27% OFF',
      image: 'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 85,
      stock: 'In Stock',
      description: 'Locally grown crisp cucumbers, pesticide-free harvest, sweet and hydrating.',
      isDeal: true,
      isFeatured: false
    },
    {
      id: 104,
      category: 'produce',
      name: 'Farm Fresh Organic Beetroot',
      nameMl: 'നാടൻ ബീറ്റ്റൂട്ട്',
      brand: 'Idukki High Range',
      weight: '500g Pack',
      price: 33,
      oldPrice: 45,
      discount: '27% OFF',
      image: 'https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 92,
      stock: 'In Stock',
      description: 'Vibrant ruby red sweet beetroots harvested from high range cool climate farms.',
      isDeal: true,
      isFeatured: false
    },
    {
      id: 105,
      category: 'produce',
      name: 'Fresh Farm Potatoes (ഉരുളക്കിഴങ്ങ്)',
      nameMl: 'ഫ്രഷ് ഉരുളക്കിഴങ്ങ്',
      brand: 'Fresh Pick',
      weight: '1 kg Pack',
      price: 33,
      oldPrice: 42,
      discount: '21% OFF',
      image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
      rating: 4.6,
      reviews: 140,
      stock: 'In Stock',
      description: 'Firm, golden skinned potatoes suitable for roast, curries, and french fries.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 106,
      category: 'produce',
      name: 'Fresh Red Onions (സവാള)',
      nameMl: 'നാടൻ സവാള (1 കി.ഗ്രാം)',
      brand: 'Fresh Pick',
      weight: '1 kg Pack',
      price: 38,
      oldPrice: 50,
      discount: '24% OFF',
      image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 200,
      stock: 'In Stock',
      description: 'Hand-sorted medium sized red onions with pungent aroma and crisp texture.',
      isDeal: false,
      isFeatured: true
    },
    {
      id: 107,
      category: 'produce',
      name: 'Country Shallots / Small Onions (ചുവന്നുള്ളി)',
      nameMl: 'നാടൻ ചെറിയ ഉള്ളി (500 ഗ്രാം)',
      brand: 'Pala Local',
      weight: '500g Pack',
      price: 45,
      oldPrice: 65,
      discount: '30% OFF',
      image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 175,
      stock: 'In Stock',
      description: 'Essential ingredient for authentic Kerala fish curries, sambar, and roast seasonings.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 108,
      category: 'produce',
      name: 'Fresh Green Chillies (പച്ചമുളക്)',
      nameMl: 'നാടൻ പച്ചമുളക് (250 ഗ്രാം)',
      brand: 'Pala Farm Direct',
      weight: '250g Pack',
      price: 18,
      oldPrice: 28,
      discount: '35% OFF',
      image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 65,
      stock: 'In Stock',
      description: 'Spicy, crunchy green chillies harvested freshly every morning.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 109,
      category: 'produce',
      name: 'Ripe Country Tomatoes (തക്കാളി)',
      nameMl: 'നാടൻ തക്കാളി (1 കി.ഗ്രാം)',
      brand: 'Fresh Harvest',
      weight: '1 kg Pack',
      price: 32,
      oldPrice: 45,
      discount: '28% OFF',
      image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 135,
      stock: 'In Stock',
      description: 'Juicy, farm-ripe red tomatoes with balanced sweetness and acidity.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 110,
      category: 'produce',
      name: 'Tender Ladies Finger / Okra (വെണ്ടക്ക)',
      nameMl: 'നാടൻ വെണ്ടക്ക (500 ഗ്രാം)',
      brand: 'Pala Farm Direct',
      weight: '500g Pack',
      price: 28,
      oldPrice: 40,
      discount: '30% OFF',
      image: 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 80,
      stock: 'In Stock',
      description: 'Fresh crisp tender okras, easy to snap and zero bitterness. Great for Meen curry & stir fries.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 111,
      category: 'produce',
      name: 'Kerala Raw Banana / Plantain (പച്ചക്കായ)',
      nameMl: 'നാടൻ പച്ചക്കായ (1 കി.ഗ്രാം)',
      brand: 'Meenachil Local',
      weight: '1 kg Pack',
      price: 44,
      oldPrice: 58,
      discount: '24% OFF',
      image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 115,
      stock: 'In Stock',
      description: 'Green cooking plantains for Thoran, Erissery, Meen curry, and homemade Upperi chips.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 112,
      category: 'produce',
      name: 'Fresh Snake Gourd (പടവലങ്ങ)',
      nameMl: 'നാടൻ പടവലങ്ങ (500 ഗ്രാം)',
      brand: 'Pala Farm Direct',
      weight: '500g Pack',
      price: 24,
      oldPrice: 35,
      discount: '31% OFF',
      image: 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&w=600&q=80',
      rating: 4.6,
      reviews: 45,
      stock: 'In Stock',
      description: 'Tender light green snake gourds, rich in water content and dietary fibers.',
      isDeal: false,
      isFeatured: false
    },

    // ----------------- 3. FRESH FRUITS (12 Items) -----------------
    {
      id: 201,
      category: 'fruits',
      name: 'Ripe Nendran Banana (ഏത്തപ്പഴം)',
      nameMl: 'നാടൻ ഏത്തപ്പഴം (1 കി.ഗ്രാം)',
      brand: 'Pala Meenachil',
      weight: 'Per Kg',
      price: 52,
      oldPrice: 68,
      discount: '23% OFF',
      image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 290,
      stock: 'In Stock',
      description: 'Naturally ripened sweet Nendran bananas. Perfect for Pazham Pori, steamed snacks, and baby food.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 202,
      category: 'fruits',
      name: 'Sweet Ruby Watermelon Kiran',
      nameMl: 'കിരൺ തണ്ണിമത്തൻ',
      brand: 'Fresh Harvest',
      weight: 'Per Kg (Whole Fruit)',
      price: 25,
      oldPrice: 40,
      discount: '38% OFF',
      image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 160,
      stock: 'In Stock',
      description: 'Deep red, seedless sweet watermelons with thin rind and high sweetness.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 203,
      category: 'fruits',
      name: 'Fresh Nagpur Seedless Sweet Oranges',
      nameMl: 'നാഗ്പൂർ ഓറഞ്ച് (1 കി.ഗ്രാം)',
      brand: 'Citrus Fresh',
      weight: '1 kg Pack',
      price: 85,
      oldPrice: 120,
      discount: '29% OFF',
      image: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 95,
      stock: 'In Stock',
      description: 'Sweet, juicy table oranges rich in Vitamin C and natural bioflavonoids.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 204,
      category: 'fruits',
      name: 'Vazhakulam GI Tagged Pineapple (കണ്ണാറ)',
      nameMl: 'വാഴക്കുളം പൈനാപ്പിൾ (1 എണ്ണം)',
      brand: 'Vazhakulam Pride',
      weight: 'Approx 1.2 kg',
      price: 55,
      oldPrice: 75,
      discount: '26% OFF',
      image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 210,
      stock: 'In Stock',
      description: 'World-famous Vazhakulam Mauritius pineapple known for sweet pleasant aroma and golden pulp.',
      isDeal: false,
      isFeatured: true
    },
    {
      id: 205,
      category: 'fruits',
      name: 'Royal Gala Crisp Red Apples',
      nameMl: 'റോയൽ ഗാല ആപ്പിൾ (1 കി.ഗ്രാം)',
      brand: 'Imported Best',
      weight: '1 kg Pack (4-5 pcs)',
      price: 175,
      oldPrice: 230,
      discount: '24% OFF',
      image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 130,
      stock: 'In Stock',
      description: 'Crisp, sweet, juicy red apples with pleasant aroma, imported under strict temperature control.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 206,
      category: 'fruits',
      name: 'Robusta Golden Bananas (റോബസ്റ്റ)',
      nameMl: 'റോബസ്റ്റ പഴം (1 കി.ഗ്രാം)',
      brand: 'Pala Farm Direct',
      weight: '1 kg Pack',
      price: 36,
      oldPrice: 48,
      discount: '25% OFF',
      image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 88,
      stock: 'In Stock',
      description: 'Sweet creamy table bananas, rich in potassium and instant energy.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 207,
      category: 'fruits',
      name: 'Fresh Red Pomegranates (അനാർ)',
      nameMl: 'മാതളനാരങ്ങ / അനാർ (1 കി.ഗ്രാം)',
      brand: 'Fresh Pick',
      weight: '1 kg Pack (3-4 pcs)',
      price: 195,
      oldPrice: 260,
      discount: '25% OFF',
      image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 78,
      stock: 'In Stock',
      description: 'Plump ruby red arils full of antioxidant-rich sweet juice.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 208,
      category: 'fruits',
      name: 'Green Seedless Grapes Box',
      nameMl: 'വിത്ത് ഇല്ലാത്ത പച്ച മുന്തിരി (500 ഗ്രാം)',
      brand: 'Fresh Pick',
      weight: '500g Box',
      price: 75,
      oldPrice: 110,
      discount: '31% OFF',
      image: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 104,
      stock: 'In Stock',
      description: 'Crisp, sweet, cleaned seedless green grapes packed hygienically.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 209,
      category: 'fruits',
      name: 'Sweet Taiwan Red Papaya',
      nameMl: 'തായ്‌വാൻ റെഡ് പപ്പായ (1 എണ്ണം)',
      brand: 'Pala Farm Direct',
      weight: 'Approx 1 kg',
      price: 38,
      oldPrice: 55,
      discount: '30% OFF',
      image: 'https://images.unsplash.com/photo-1617112848923-cc2234396a8d?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 62,
      stock: 'In Stock',
      description: 'Naturally sweetened red pulp papaya rich in papain enzymes and digestive health benefits.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 210,
      category: 'fruits',
      name: 'Fresh Guava Allahabad Safeda (പേരക്ക)',
      nameMl: 'നാടൻ പേരക്ക (1 കി.ഗ്രാം)',
      brand: 'Fresh Harvest',
      weight: '1 kg Pack',
      price: 65,
      oldPrice: 85,
      discount: '23% OFF',
      image: 'https://images.unsplash.com/photo-1536511135898-0283b1c67675?auto=format&fit=crop&w=600&q=80',
      rating: 4.6,
      reviews: 44,
      stock: 'In Stock',
      description: 'Crunchy sweet white flesh guavas packed with dietary fiber and Vitamin C.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 211,
      category: 'fruits',
      name: 'Premium California Almonds (ബദാം)',
      nameMl: 'കാലിഫോർണിയ ബദാം (500 ഗ്രാം)',
      brand: 'NutriKing',
      weight: '500g Pouch',
      price: 399,
      oldPrice: 520,
      discount: '23% OFF',
      image: 'https://images.unsplash.com/photo-1508061252224-4039b89345ed?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 180,
      stock: 'In Stock',
      description: 'Whole crunchy California almonds, 100% natural, high in protein and vitamin E.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 212,
      category: 'fruits',
      name: 'Whole Cashew Nuts W240 (കശുവണ്ടി)',
      nameMl: 'നാടൻ കശുവണ്ടിപ്പരിപ്പ് (500 ഗ്രാം)',
      brand: 'Kerala Cashew Co',
      weight: '500g Pouch',
      price: 430,
      oldPrice: 580,
      discount: '25% OFF',
      image: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 145,
      stock: 'In Stock',
      description: 'Grade W240 premium whole cashews from Kollam. Creamy sweet taste for cooking & snacking.',
      isDeal: false,
      isFeatured: false
    },

    // ----------------- 4. MEAT & FRESH FISH (12 Items) -----------------
    {
      id: 301,
      category: 'meat-fish',
      name: 'Fresh Pearl Spot / Karimeen (കരിമീൻ)',
      nameMl: 'നാടൻ കരിമീൻ (1 കി.ഗ്രാം)',
      brand: 'Kumarakom Catch',
      weight: '1 kg (Cleaned & Gutted)',
      price: 520,
      oldPrice: 650,
      discount: '20% OFF',
      image: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 215,
      stock: 'In Stock',
      description: 'Backwater fresh Karimeen from Vembanad lake. Ideal for traditional Kerala Karimeen Pollichathu.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 302,
      category: 'meat-fish',
      name: 'Fresh Farm Chicken Curry Cut (സ്കിൻലെസ്)',
      nameMl: 'ഫ്രഷ് ചിക്കൻ കറി കട്ട് (1 കി.ഗ്രാം)',
      brand: 'Golden Fresh',
      weight: '1 kg Pack',
      price: 185,
      oldPrice: 240,
      discount: '22% OFF',
      image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 340,
      stock: 'In Stock',
      description: 'Antibiotic-residue free tender farm chicken, washed and cut into uniform pieces for curry.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 303,
      category: 'meat-fish',
      name: 'Seer Fish Steaks / Neymeen (നെയ്മീൻ)',
      nameMl: 'നെയ്മീൻ സ്ലൈസ് (500 ഗ്രാം)',
      brand: 'Arabian Sea Catch',
      weight: '500g Pack (Cleaned Slices)',
      price: 460,
      oldPrice: 580,
      discount: '20% OFF',
      image: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 185,
      stock: 'In Stock',
      description: 'King seer fish neatly sliced into steaks. Best for spicy tawa fry and rich coconut gravy.',
      isDeal: false,
      isFeatured: true
    },
    {
      id: 304,
      category: 'meat-fish',
      name: 'Fresh Tiger Prawns / Chemmeen (ചെമ്മീൻ)',
      nameMl: 'ടൈഗർ ചെമ്മീൻ (500 ഗ്രാം)',
      brand: 'Kerala Coastal',
      weight: '500g (Peeled & Deveined)',
      price: 340,
      oldPrice: 450,
      discount: '24% OFF',
      image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 125,
      stock: 'In Stock',
      description: 'Sweet, juicy medium-large prawns cleaned and ready to cook Chemmeen Roast.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 305,
      category: 'meat-fish',
      name: 'Delicious Chicken Nuggets Family Pack',
      nameMl: 'ഡിലീഷ്യസ് ചിക്കൻ നഗ്ഗറ്റ്സ് (1 കി.ഗ്രാം)',
      brand: 'Delicious',
      weight: '1 kg Box',
      price: 349,
      oldPrice: 450,
      discount: '22% OFF',
      image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 88,
      stock: 'In Stock',
      description: 'Crispy, golden coated chicken bites ready in 4 minutes for evening kids snacks.',
      isDeal: true,
      isFeatured: false
    },
    {
      id: 306,
      category: 'meat-fish',
      name: 'Tender Mutton Curry Cut (ആട്ടിറച്ചി)',
      nameMl: 'ഫ്രഷ് ആട്ടിറച്ചി (500 ഗ്രാം)',
      brand: 'Golden Meat Hub',
      weight: '500g Pack',
      price: 440,
      oldPrice: 530,
      discount: '17% OFF',
      image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 150,
      stock: 'In Stock',
      description: 'Fresh grass-fed young goat meat cut into pieces for spicy Kerala Mutton Stew & Roast.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 307,
      category: 'meat-fish',
      name: 'Fresh Sardine / Mathi (ചാള / മത്തി)',
      nameMl: 'ഫ്രഷ് മത്തി (1 കി.ഗ്രാം)',
      brand: 'Coastal Fresh',
      weight: '1 kg Pack (Cleaned)',
      price: 160,
      oldPrice: 210,
      discount: '23% OFF',
      image: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 210,
      stock: 'In Stock',
      description: 'Omega-3 rich fresh sea sardines. Cleaned and gutted for quick spicy Mathi curry with Kudampuli.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 308,
      category: 'meat-fish',
      name: 'Fresh Mackerel / Ayala (അയില)',
      nameMl: 'ഫ്രഷ് അയില (1 കി.ഗ്രാം)',
      brand: 'Coastal Fresh',
      weight: '1 kg Pack',
      price: 220,
      oldPrice: 280,
      discount: '21% OFF',
      image: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 165,
      stock: 'In Stock',
      description: 'Fresh marine mackerels, delicious when fried crisp with red chilli turmeric paste.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 309,
      category: 'meat-fish',
      name: 'Chicken Breast Boneless Fillets',
      nameMl: 'ചിക്കൻ ബ്രെസ്റ്റ് ബോൺലെസ്സ് (500 ഗ്രാം)',
      brand: 'Golden Fresh',
      weight: '500g Pack',
      price: 160,
      oldPrice: 210,
      discount: '23% OFF',
      image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 90,
      stock: 'In Stock',
      description: 'Lean high-protein chicken fillets, trimmed and cleaned for salads and grills.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 310,
      category: 'meat-fish',
      name: 'Crispy Chicken Cutlets (Breaded)',
      nameMl: 'ചിക്കൻ കട്ട്ലറ്റ് (6 എണ്ണം)',
      brand: 'Delicious',
      weight: '300g (Pack of 6)',
      price: 140,
      oldPrice: 180,
      discount: '22% OFF',
      image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 65,
      stock: 'In Stock',
      description: 'Spiced minced chicken and potato cutlets crumbed in bread flakes. Ready to fry.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 311,
      category: 'meat-fish',
      name: 'Fresh Anchovy / Natholi (നത്തോലി)',
      nameMl: 'ഫ്രഷ് നത്തോലി (500 ഗ്രാം)',
      brand: 'Coastal Fresh',
      weight: '500g (Cleaned)',
      price: 130,
      oldPrice: 170,
      discount: '23% OFF',
      image: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 80,
      stock: 'In Stock',
      description: 'Crispy frying anchovy fish rich in calcium and natural minerals.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 312,
      category: 'meat-fish',
      name: 'Fresh Chicken Drumsticks (4 pcs)',
      nameMl: 'ചിക്കൻ ഡ്രംസ്റ്റിക്സ് (4 എണ്ണം)',
      brand: 'Golden Fresh',
      weight: '500g Pack',
      price: 155,
      oldPrice: 195,
      discount: '20% OFF',
      image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 110,
      stock: 'In Stock',
      description: 'Juicy chicken leg drumsticks with smooth skin for roasting and tandoor recipes.',
      isDeal: false,
      isFeatured: false
    },

    // ----------------- 5. DAIRY & EGGS (12 Items) -----------------
    {
      id: 401,
      category: 'dairy',
      name: 'Malanadu Pure High Range Cow Ghee',
      nameMl: 'മലനാട് ശുദ്ധമായ പശുവിൻ നെയ്യ്',
      brand: 'Malanadu',
      weight: '500 ml Jar',
      price: 329,
      oldPrice: 400,
      discount: '18% OFF',
      image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 310,
      stock: 'In Stock',
      description: 'Traditional slow-churned pure cow ghee from Idukki high-range dairy societies. Rich golden aroma.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 402,
      category: 'dairy',
      name: 'Milky Mist Fresh Paneer Block',
      nameMl: 'മിൽക്കി മിസ്റ്റ് ഫ്രഷ് പനീർ (400 ഗ്രാം)',
      brand: 'Milky Mist',
      weight: '400g Pack',
      price: 165,
      oldPrice: 210,
      discount: '21% OFF',
      image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 180,
      stock: 'In Stock',
      description: 'Soft, creamy paneer made from 100% cow milk with zero preservatives.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 403,
      category: 'dairy',
      name: 'Farm Fresh White Table Eggs (30 Tray)',
      nameMl: 'ഫ്രഷ് മുട്ട (30 എണ്ണത്തിന്റെ ട്രേ)',
      brand: 'Golden Farm',
      weight: '30 Eggs Tray',
      price: 195,
      oldPrice: 250,
      discount: '22% OFF',
      image: 'https://images.unsplash.com/photo-1528750997573-59b89d56f4f7?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 420,
      stock: 'In Stock',
      description: 'Graded, high protein fresh poultry eggs delivered straight from certified local farms.',
      isDeal: false,
      isFeatured: true
    },
    {
      id: 404,
      category: 'dairy',
      name: 'Amul Salted Table Butter',
      nameMl: 'അമുൽ ബട്ടർ (500 ഗ്രാം)',
      brand: 'Amul',
      weight: '500g Block',
      price: 275,
      oldPrice: 295,
      discount: '7% OFF',
      image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 350,
      stock: 'In Stock',
      description: 'India’s most loved creamy butter, made from fresh cream. The classic taste of butter.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 405,
      category: 'dairy',
      name: 'Milma Toned Fresh Milk (പച്ച പാക്കറ്റ്)',
      nameMl: 'മിൽമ ടോൺഡ് പാൽ (500 മില്ലി)',
      brand: 'Milma',
      weight: '500 ml Pouch',
      price: 26,
      oldPrice: 26,
      discount: 'MRP',
      image: 'https://images.unsplash.com/photo-1528750997573-59b89d56f4f7?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 510,
      stock: 'In Stock',
      description: 'Pasteurised, homogenised toned cow milk from Kerala cooperative milk marketing federation.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 406,
      category: 'dairy',
      name: 'Malanadu Cow Butter (ഉരുക്കാത്ത വെണ്ണ)',
      nameMl: 'മലനാട് പശുവിൻ വെണ്ണ (500 ഗ്രാം)',
      brand: 'Malanadu',
      weight: '500g Pack',
      price: 290,
      oldPrice: 340,
      discount: '15% OFF',
      image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 95,
      stock: 'In Stock',
      description: 'Unsalted traditional churned white butter, ideal for home ghee preparation and sweets.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 407,
      category: 'dairy',
      name: 'Milky Mist Plain Greek Yogurt / Curd',
      nameMl: 'മിൽക്കി മിസ്റ്റ് തൈര് (1 കി.ഗ്രാം)',
      brand: 'Milky Mist',
      weight: '1 kg Tub',
      price: 110,
      oldPrice: 135,
      discount: '18% OFF',
      image: 'https://images.unsplash.com/photo-1528750997573-59b89d56f4f7?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 80,
      stock: 'In Stock',
      description: 'Thick, creamy set curd made from pure milk with active probiotic cultures.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 408,
      category: 'dairy',
      name: 'Amul Processed Cheese Slices',
      nameMl: 'അമുൽ ചീസ് സ്ലൈസുകൾ (200 ഗ്രാം)',
      brand: 'Amul',
      weight: '200g (10 Slices)',
      price: 140,
      oldPrice: 160,
      discount: '12% OFF',
      image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 160,
      stock: 'In Stock',
      description: 'Individually wrapped cheese slices that melt smoothly in sandwiches and burgers.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 409,
      category: 'dairy',
      name: 'Local Organic Country Chicken Eggs (നാടൻ കോഴിമുട്ട)',
      nameMl: 'നാടൻ കോഴിമുട്ട (10 എണ്ണം)',
      brand: 'Pala Country Farm',
      weight: 'Pack of 10',
      price: 110,
      oldPrice: 140,
      discount: '21% OFF',
      image: 'https://images.unsplash.com/photo-1528750997573-59b89d56f4f7?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 130,
      stock: 'In Stock',
      description: 'Free-range country brown eggs with deep yellow-orange yolks, rich in nutrients.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 410,
      category: 'dairy',
      name: 'Amul Fresh Whipping Cream',
      nameMl: 'അമുൽ ഫ്രഷ് ക്രീം (250 മില്ലി)',
      brand: 'Amul',
      weight: '250 ml Tetra',
      price: 65,
      oldPrice: 75,
      discount: '13% OFF',
      image: 'https://images.unsplash.com/photo-1528750997573-59b89d56f4f7?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 70,
      stock: 'In Stock',
      description: 'Sterilised low fat cream for fruit salads, gravies, desserts, and coffee.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 411,
      category: 'dairy',
      name: 'Amul Kool Kesar Badam Milk Can',
      nameMl: 'അമുൽ കൂൾ ബദാം മിൽക്ക് (200 മില്ലി)',
      brand: 'Amul',
      weight: '200 ml Can',
      price: 35,
      oldPrice: 40,
      discount: '12% OFF',
      image: 'https://images.unsplash.com/photo-1528750997573-59b89d56f4f7?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 90,
      stock: 'In Stock',
      description: 'Chilled refreshing milk beverage flavoured with real saffron and almond pieces.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 412,
      category: 'dairy',
      name: 'Milky Mist Mozzarella Pizza Cheese Shredded',
      nameMl: 'മൊസറെല്ല ചീസ് (200 ഗ്രാം)',
      brand: 'Milky Mist',
      weight: '200g Pouch',
      price: 155,
      oldPrice: 190,
      discount: '18% OFF',
      image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 85,
      stock: 'In Stock',
      description: 'Pre-shredded 100% mozzarella cheese with superior stretch for pizzas and gratins.',
      isDeal: false,
      isFeatured: false
    },

    // ----------------- 6. BAKERY & SNACKS (12 Items) -----------------
    {
      id: 501,
      category: 'bakery',
      name: 'Kerala Banana Chips in Pure Coconut Oil',
      nameMl: 'നാടൻ വറുത്ത നേന്ത്രക്കായ ചിപ്സ്',
      brand: 'Golden Bakers Pala',
      weight: '400g Pouch',
      price: 155,
      oldPrice: 200,
      discount: '22% OFF',
      image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 380,
      stock: 'In Stock',
      description: 'Crispy wafer-thin Nendran banana slices fried in pure fragrant coconut oil with turmeric and salt.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 502,
      category: 'bakery',
      name: 'Golden Fresh Milk Bread Loaf',
      nameMl: 'ഫ്രഷ് മിൽക്ക് ബ്രെഡ് (400 ഗ്രാം)',
      brand: 'Golden Bakers',
      weight: '400g Sliced Loaf',
      price: 40,
      oldPrice: 50,
      discount: '20% OFF',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 190,
      stock: 'In Stock',
      description: 'Baked fresh daily at 6 AM. Ultra soft, fluffy milk bread slices for morning toast.',
      isDeal: false,
      isFeatured: true
    },
    {
      id: 503,
      category: 'bakery',
      name: 'Kerala Sharkkara Varatti (ശർക്കരവരട്ടി)',
      nameMl: 'നാടൻ ശർക്കരവരട്ടി (400 ഗ്രാം)',
      brand: 'Golden Bakers',
      weight: '400g Pouch',
      price: 175,
      oldPrice: 220,
      discount: '20% OFF',
      image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 145,
      stock: 'In Stock',
      description: 'Thick cut banana chips coated with pure jaggery, dried ginger (chukku) and cardamom powder.',
      isDeal: false,
      isFeatured: true
    },
    {
      id: 504,
      category: 'bakery',
      name: 'Britannia Toastea Premium Wheat Rusk',
      nameMl: 'ബ്രിട്ടാനിയ വീറ്റ് റസ്ക് (400 ഗ്രാം)',
      brand: 'Britannia',
      weight: '400g Pack',
      price: 65,
      oldPrice: 80,
      discount: '19% OFF',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 110,
      stock: 'In Stock',
      description: 'Crispy, crunchy double baked wheat toasts flavoured with gentle hints of cardamom.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 505,
      category: 'bakery',
      name: 'Kerala Spicy Mixture (സ്പെഷ്യൽ മിക്സ്ചർ)',
      nameMl: 'സ്പെഷ്യൽ മിക്സ്ചർ (500 ഗ്രാം)',
      brand: 'Golden Bakers',
      weight: '500g Pouch',
      price: 120,
      oldPrice: 160,
      discount: '25% OFF',
      image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 215,
      stock: 'In Stock',
      description: 'Traditional tea-time mix with boondi, fried peanuts, roasted curry leaves, and garlic.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 506,
      category: 'bakery',
      name: 'Plum Cake Premium Rich Fruit Cake',
      nameMl: 'പ്ലം കേക്ക് (500 ഗ്രാം)',
      brand: 'Golden Bakers',
      weight: '500g Box',
      price: 240,
      oldPrice: 300,
      discount: '20% OFF',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 130,
      stock: 'In Stock',
      description: 'Loaded with caramelised raisins, tutty fruity, candied ginger, and aromatic Christmas spices.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 507,
      category: 'bakery',
      name: 'Britannia Good Day Cashew Cookies',
      nameMl: 'ബ്രിട്ടാനിയ ഗുഡ് ഡേ കാഷ്യൂ (600 ഗ്രാം)',
      brand: 'Britannia',
      weight: '600g Value Pack',
      price: 110,
      oldPrice: 140,
      discount: '21% OFF',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 280,
      stock: 'In Stock',
      description: 'Rich buttery cookies with the crunch of handpicked cashews and pleasant vanilla aroma.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 508,
      category: 'bakery',
      name: 'Parle-G Gold Original Glucose Biscuits',
      nameMl: 'പാർലെ-ജി ഗോൾഡ് ബിസ്കറ്റ് (1 കി.ഗ്രാം)',
      brand: 'Parle',
      weight: '1 kg Family Pack',
      price: 115,
      oldPrice: 140,
      discount: '18% OFF',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 320,
      stock: 'In Stock',
      description: 'Classic energy rich wheat & milk glucose biscuits, beloved companion with hot tea.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 509,
      category: 'bakery',
      name: 'Fresh Brown Wheat Bread Loaf',
      nameMl: 'ബ്രൗൺ വീറ്റ് ബ്രെഡ് (400 ഗ്രാം)',
      brand: 'Golden Bakers',
      weight: '400g Loaf',
      price: 45,
      oldPrice: 55,
      discount: '18% OFF',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 80,
      stock: 'In Stock',
      description: 'High-fiber whole wheat sliced bread with zero added refined maida.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 510,
      category: 'bakery',
      name: 'Jackfruit Chips (ചക്ക വറുത്തത്)',
      nameMl: 'നാടൻ ചക്ക ചിപ്സ് (250 ഗ്രാം)',
      brand: 'Golden Bakers',
      weight: '250g Pouch',
      price: 160,
      oldPrice: 210,
      discount: '24% OFF',
      image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 140,
      stock: 'In Stock',
      description: 'Seasonal speciality from Pala jackfruit trees, fried crispy in coconut oil.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 511,
      category: 'bakery',
      name: 'Shabari Mixed Fruit Jam',
      nameMl: 'ശബരി മിക്സഡ് ഫ്രൂട്ട് ജാം (500 ഗ്രാം)',
      brand: 'Shabari',
      weight: '500g Jar',
      price: 125,
      oldPrice: 155,
      discount: '19% OFF',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 90,
      stock: 'In Stock',
      description: 'Juicy fruit spread with real papaya, mango, pineapple, and apple pulps.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 512,
      category: 'bakery',
      name: 'Sunfeast Dark Fantasy Choco Fills',
      nameMl: 'ഡാർക്ക് ഫാന്റസി ചോക്കോ ഫിൽസ് (300 ഗ്രാം)',
      brand: 'Sunfeast',
      weight: '300g Box',
      price: 130,
      oldPrice: 165,
      discount: '21% OFF',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 240,
      stock: 'In Stock',
      description: 'Crispy cookie shell filled with molten rich chocolate cream.',
      isDeal: false,
      isFeatured: false
    },

    // ----------------- 7. HOUSEHOLD & CLEANING (12 Items) -----------------
    {
      id: 601,
      category: 'household',
      name: 'Surf Excel Matic Front Load Detergent Liquid',
      nameMl: 'സർഫ് എക്സൽ ലിക്വിഡ് (2 ലിറ്റർ)',
      brand: 'Surf Excel',
      weight: '2 Litre Bottle',
      price: 430,
      oldPrice: 520,
      discount: '17% OFF',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 290,
      stock: 'In Stock',
      description: 'Superior stain removal formula designed for front load washing machines without residue.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 602,
      category: 'household',
      name: 'Vim Dishwash Gel Lemon Refill Pouch',
      nameMl: 'വിം ലിക്വിഡ് ജെൽ (2 ലിറ്റർ)',
      brand: 'Vim',
      weight: '2 Litre Pouch',
      price: 360,
      oldPrice: 440,
      discount: '18% OFF',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 310,
      stock: 'In Stock',
      description: 'Cuts through tough oil and masala grease on stainless steel, non-stick, and glassware.',
      isDeal: false,
      isFeatured: true
    },
    {
      id: 603,
      category: 'household',
      name: 'Lizol Floral Surface & Floor Cleaner Disinfectant',
      nameMl: 'ലൈസോൾ ഫ്ലോർ ക്ലീനർ (2 ലിറ്റർ)',
      brand: 'Lizol',
      weight: '2 Litre Bottle',
      price: 345,
      oldPrice: 420,
      discount: '18% OFF',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 260,
      stock: 'In Stock',
      description: 'Kills 99.9% germs, leaves long lasting refreshing floral fragrance on tiled floors.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 604,
      category: 'household',
      name: 'Harpic Power Plus Toilet Cleaner Liquid',
      nameMl: 'ഹാർപിക് ക്ലീനർ (1 ലിറ്റർ)',
      brand: 'Harpic',
      weight: '1 Litre Bottle',
      price: 185,
      oldPrice: 225,
      discount: '18% OFF',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 190,
      stock: 'In Stock',
      description: 'Thick formula cleans limescale, yellow stains, and gives 10x better stain removal.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 605,
      category: 'household',
      name: 'Comfort After Wash Fabric Conditioner Lily',
      nameMl: 'കംഫർട്ട് ഫാബ്രിക് കണ്ടീഷണർ (860 മില്ലി)',
      brand: 'Comfort',
      weight: '860 ml Bottle',
      price: 215,
      oldPrice: 260,
      discount: '17% OFF',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 140,
      stock: 'In Stock',
      description: 'Unbeatable shine, softness, and 14 days fragrance for clothes and towels.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 606,
      category: 'household',
      name: 'Dettol Original Antiseptic Liquid Disinfectant',
      nameMl: 'ഡെറ്റോൾ ആന്റിസെപ്റ്റിക് (550 മില്ലി)',
      brand: 'Dettol',
      weight: '550 ml Bottle',
      price: 199,
      oldPrice: 235,
      discount: '15% OFF',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 410,
      stock: 'In Stock',
      description: 'Trusted personal hygiene and household protection against infection and germs.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 607,
      category: 'household',
      name: 'Godrej Aer Pocket Bathroom Fragrance (Pack of 3)',
      nameMl: 'എയർ പോക്കറ്റ് ഫ്രെഷനർ (3 എണ്ണം)',
      brand: 'Godrej Aer',
      weight: 'Pack of 3 x 10g',
      price: 155,
      oldPrice: 195,
      discount: '21% OFF',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 95,
      stock: 'In Stock',
      description: 'Slim gel pocket technology delivering fresh aroma for up to 30 days per unit.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 608,
      category: 'household',
      name: 'Scotch-Brite Heavy Duty Sponge Scrub (Pack of 3)',
      nameMl: 'സ്കോച്ച് ബ്രൈറ്റ് സ്പോഞ്ച് സ്ക്രബ് (3 എണ്ണം)',
      brand: 'Scotch-Brite',
      weight: 'Pack of 3',
      price: 90,
      oldPrice: 115,
      discount: '22% OFF',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 160,
      stock: 'In Stock',
      description: 'Stain-cutting scrub on one side and absorbent sponge on the other for gentle dishwashing.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 609,
      category: 'household',
      name: 'All Out Ultra Mosquito Repellent Liquid (Refill 3+1)',
      nameMl: 'ഓൾ ഔട്ട് മോസ്കിറ്റോ റീഫിൽ (4 എണ്ണം)',
      brand: 'All Out',
      weight: 'Pack of 4 Refills',
      price: 245,
      oldPrice: 320,
      discount: '23% OFF',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 210,
      stock: 'In Stock',
      description: 'High-power mosquito protection mode for sound and peaceful night sleep.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 610,
      category: 'household',
      name: 'Cycle Pure Agarbathies Yagna Sandal Incense',
      nameMl: 'സൈക്കിൾ അഗർബത്തി ചന്ദനം (പാക്ക്)',
      brand: 'Cycle Pure',
      weight: '250 Sticks Box',
      price: 130,
      oldPrice: 165,
      discount: '21% OFF',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 175,
      stock: 'In Stock',
      description: 'Soothing natural sandalwood temple fragrance for morning prayer and meditation.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 611,
      category: 'household',
      name: 'Origami Soft 2-Ply Kitchen Tissue Paper Roll (Pack of 4)',
      nameMl: 'ഒറിഗാമി കിച്ചൻ ടിഷ്യൂ റോൾ (4 എണ്ണം)',
      brand: 'Origami',
      weight: 'Pack of 4 Rolls',
      price: 160,
      oldPrice: 210,
      discount: '24% OFF',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 90,
      stock: 'In Stock',
      description: 'Super absorbent food-safe virgin pulp paper for soaking oil and wiping counters.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 612,
      category: 'household',
      name: 'Colin Glass & Multi-Surface Cleaner Spray',
      nameMl: 'കോളിൻ ഗ്ലാസ് ക്ലീനർ സ്പ്രേ (500 മില്ലി)',
      brand: 'Colin',
      weight: '500 ml Trigger Spray',
      price: 99,
      oldPrice: 120,
      discount: '18% OFF',
      image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 130,
      stock: 'In Stock',
      description: 'Provides 2x more shine on glass windows, TV screens, car mirrors, and refrigerators.',
      isDeal: false,
      isFeatured: false
    },

    // ----------------- 8. BEVERAGES & TEA (12 Items) -----------------
    {
      id: 701,
      category: 'beverages',
      name: 'Eastea Special Dust Tea (Highland Blend)',
      nameMl: 'ഈസ്റ്റീ സ്പെഷ്യൽ ഡസ്റ്റ് ചായപ്പൊടി',
      brand: 'Eastea',
      weight: '500g Pack',
      price: 199,
      oldPrice: 250,
      discount: '20% OFF',
      image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 320,
      stock: 'In Stock',
      description: 'Rich amber liquor and intense strong aroma from high altitude Munnar & Wayanad tea gardens.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 702,
      category: 'beverages',
      name: 'AVT Premium Dust Tea Extra Strong',
      nameMl: 'എ.വി.ടി പ്രീമിയം ചായപ്പൊടി (500 ഗ്രാം)',
      brand: 'AVT',
      weight: '500g Pack',
      price: 215,
      oldPrice: 260,
      discount: '17% OFF',
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 210,
      stock: 'In Stock',
      description: 'Kerala’s trusted household cup of tea with deep red strength and authentic taste.',
      isDeal: false,
      isFeatured: true
    },
    {
      id: 703,
      category: 'beverages',
      name: 'Bru Instant Coffee Jar',
      nameMl: 'ബ്രൂ ഇൻസ്റ്റന്റ് കോഫി (200 ഗ്രാം)',
      brand: 'Bru',
      weight: '200g Glass Jar',
      price: 360,
      oldPrice: 425,
      discount: '15% OFF',
      image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 190,
      stock: 'In Stock',
      description: 'Fine blend of 70% coffee and 30% chicory, roasted to perfection for south Indian filter aroma.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 704,
      category: 'beverages',
      name: 'Horlicks Classic Malt Health Drink',
      nameMl: 'ഹോർലിക്സ് മാൾട്ട് പൗഡർ (1 കി.ഗ്രാം)',
      brand: 'Horlicks',
      weight: '1 kg Refill Pack',
      price: 385,
      oldPrice: 460,
      discount: '16% OFF',
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 240,
      stock: 'In Stock',
      description: 'Packed with 23 vital nutrients to support growth, immunity, and bone health in children.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 705,
      category: 'beverages',
      name: 'Boost Energy Drink Health Supplement',
      nameMl: 'ബൂസ്റ്റ് എനർജി ഡ്രിങ്ക് (1 കി.ഗ്രാം)',
      brand: 'Boost',
      weight: '1 kg Jar',
      price: 430,
      oldPrice: 510,
      discount: '16% OFF',
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 180,
      stock: 'In Stock',
      description: 'Delicious chocolate flavoured malt drink with Enviro-Nutrients for active energy.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 706,
      category: 'beverages',
      name: 'Nescafe Classic 100% Pure Instant Coffee',
      nameMl: 'നെസ്‌കഫേ ഇൻസ്റ്റന്റ് കോഫി (100 ഗ്രാം)',
      brand: 'Nescafe',
      weight: '100g Glass Jar',
      price: 240,
      oldPrice: 280,
      discount: '14% OFF',
      image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 220,
      stock: 'In Stock',
      description: 'Pure medium-dark roasted Robusta coffee beans with signature awakening aroma.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 707,
      category: 'beverages',
      name: 'Real Fruit Power Alphonso Mango Juice',
      nameMl: 'റിയൽ മാംഗോ ജ്യൂസ് (1 ലിറ്റർ)',
      brand: 'Real',
      weight: '1 Litre Tetra',
      price: 110,
      oldPrice: 135,
      discount: '18% OFF',
      image: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b7?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 130,
      stock: 'In Stock',
      description: 'Thick, sweet nectar prepared from luscious Ratnagiri Alphonso mangoes.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 708,
      category: 'beverages',
      name: 'Tropicana 100% Orange Juice No Added Sugar',
      nameMl: 'ട്രോപിക്കാന ഓറഞ്ച് ജ്യൂസ് (1 ലിറ്റർ)',
      brand: 'Tropicana',
      weight: '1 Litre Tetra',
      price: 130,
      oldPrice: 160,
      discount: '19% OFF',
      image: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b7?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 95,
      stock: 'In Stock',
      description: 'Pure squeezed sweet orange juice without artificial preservatives or refined sugars.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 709,
      category: 'beverages',
      name: 'Paper Boat Aamras Mango Drink (Pack of 6)',
      nameMl: 'പേപ്പർ ബോട്ട് ആംറസ് (6 എണ്ണം)',
      brand: 'Paper Boat',
      weight: '6 x 200 ml Pack',
      price: 180,
      oldPrice: 240,
      discount: '25% OFF',
      image: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b7?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 110,
      stock: 'In Stock',
      description: 'Nostalgic home-style mango treat made with 45% real mango pulp.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 710,
      category: 'beverages',
      name: 'Kinley Packaged Drinking Water 20L Can with Dispenser',
      nameMl: 'കിൻലി കുടിവെള്ളം (20 ലിറ്റർ ക്യാൻ)',
      brand: 'Kinley',
      weight: '20 Litre Can',
      price: 85,
      oldPrice: 100,
      discount: '15% OFF',
      image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 450,
      stock: 'In Stock',
      description: 'Reverse osmosis purified water with added minerals for pure daily family hydration in Pala.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 711,
      category: 'beverages',
      name: 'Kanan Devan Strong CTC Tea',
      nameMl: 'കണ്ണൻ ദേവൻ ചായപ്പൊടി (500 ഗ്രാം)',
      brand: 'Tata Tea',
      weight: '500g Pack',
      price: 185,
      oldPrice: 220,
      discount: '16% OFF',
      image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 140,
      stock: 'In Stock',
      description: 'Classic Tata Tea blend from Munnar high ranges with robust body and pleasant color.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 712,
      category: 'beverages',
      name: 'Rasna Fruit Plus Orange Concentrate Pouch',
      nameMl: 'റസ്ന ഓറഞ്ച് കോൺസെൻട്രേറ്റ് (500 ഗ്രാം)',
      brand: 'Rasna',
      weight: '500g Pouch (Makes 32 Glasses)',
      price: 120,
      oldPrice: 150,
      discount: '20% OFF',
      image: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b7?auto=format&fit=crop&w=600&q=80',
      rating: 4.6,
      reviews: 75,
      stock: 'In Stock',
      description: 'Instant summer drink mix enriched with 21 vitamins and minerals with fruit juice powder.',
      isDeal: false,
      isFeatured: false
    },

    // ----------------- 9. ELECTRONICS & APPLIANCES (12 Items) -----------------
    {
      id: 801,
      category: 'electronics',
      name: 'Preethi Zodiac 750W Mixer Grinder (5 Jars)',
      nameMl: 'പ്രീതി സോഡിയാക് മിക്സി (750W)',
      brand: 'Preethi',
      weight: '5 Jars Set',
      price: 7499,
      oldPrice: 9999,
      discount: '25% OFF',
      image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 180,
      stock: 'In Stock',
      description: 'India’s No.1 mixer with Master Chef food processor jar for chopping, slicing, atta kneading and citrus juicing.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 802,
      category: 'electronics',
      name: 'Prestige Svachh Deluxe Hard Anodised Pressure Cooker 5L',
      nameMl: 'പ്രസ്റ്റീജ് കുക്കർ (5 ലിറ്റർ)',
      brand: 'Prestige',
      weight: '5 Litre Capacity',
      price: 2199,
      oldPrice: 2895,
      discount: '24% OFF',
      image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 240,
      stock: 'In Stock',
      description: 'Spillage control deep lid design with durable induction compatible base and safety valve.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 803,
      category: 'electronics',
      name: 'Butterfly Jet Elite 750W Mixer Grinder (4 Jars)',
      nameMl: 'ബട്ടർഫ്ലൈ മിക്സി 750W (4 ജാറുകൾ)',
      brand: 'Butterfly',
      weight: '4 Jars Set',
      price: 3299,
      oldPrice: 4899,
      discount: '33% OFF',
      image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 155,
      stock: 'In Stock',
      description: 'Heavy duty copper motor with stainless steel blades for fine idli batter, coconut grinding and spice masalas.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 804,
      category: 'electronics',
      name: 'Philips Daily Collection 1.5L Electric Kettle',
      nameMl: 'ഫിലിപ്സ് ഇലക്ട്രിക് കെറ്റിൽ (1.5 ലിറ്റർ)',
      brand: 'Philips',
      weight: '1.5 Litre (1800W)',
      price: 1399,
      oldPrice: 1895,
      discount: '26% OFF',
      image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 210,
      stock: 'In Stock',
      description: 'Stainless steel body with automatic boil-dry protection and 360 degree cordless pirouette base.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 805,
      category: 'electronics',
      name: "Havells D'lite 1000W Heavyweight Dry Iron Box",
      nameMl: 'ഹാവെൽസ് അയൺ ബോക്സ് (1000W)',
      brand: 'Havells',
      weight: '1000W Heavy Base',
      price: 1049,
      oldPrice: 1450,
      discount: '28% OFF',
      image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 130,
      stock: 'In Stock',
      description: 'German non-stick coating with thermal fuse safety for crisp crease removal on cotton mundu and shirts.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 806,
      category: 'electronics',
      name: 'Prestige Induction Cooktop PIC 20.0 (1600W)',
      nameMl: 'പ്രസ്റ്റീജ് ഇൻഡക്ഷൻ കുക്ക്ടോപ്പ് (1600W)',
      brand: 'Prestige',
      weight: '1600W Power',
      price: 2499,
      oldPrice: 3495,
      discount: '28% OFF',
      image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 175,
      stock: 'In Stock',
      description: 'Push button controls, Indian menu presets, anti-magnetic wall, and automatic voltage regulator.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 807,
      category: 'electronics',
      name: 'Hawkins Futura Hard Anodised Dosa Tawa (28 cm)',
      nameMl: 'ഹോക്കിൻസ് ദോശ തവ (28 cm)',
      brand: 'Hawkins',
      weight: '28 cm Diameter',
      price: 1199,
      oldPrice: 1450,
      discount: '17% OFF',
      image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 230,
      stock: 'In Stock',
      description: 'Heavy 4.88 mm thick base for even heat conduction and crispy golden brown ghee dosas.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 808,
      category: 'electronics',
      name: 'V-Guard High Speed 1200mm Ceiling Fan (Ivory)',
      nameMl: 'വി-ഗാർഡ് സീലിംഗ് ഫാൻ (1200mm)',
      brand: 'V-Guard',
      weight: '1200 mm Sweep',
      price: 1899,
      oldPrice: 2490,
      discount: '24% OFF',
      image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 195,
      stock: 'In Stock',
      description: 'High air delivery with double ball bearings and rust resistant aluminium powder coated blades.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 809,
      category: 'electronics',
      name: 'boAt Airdopes 141 True Wireless Earbuds',
      nameMl: 'ബോട്ട് എയർഡോപ്സ് വയർലെസ്സ് ഇയർബഡ്സ്',
      brand: 'boAt',
      weight: '42 Hours Playback',
      price: 1199,
      oldPrice: 2990,
      discount: '60% OFF',
      image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
      rating: 4.6,
      reviews: 580,
      stock: 'In Stock',
      description: 'ENx environmental noise cancelling mic, fast ASAP charging, and deep signature boAt bass.',
      isDeal: true,
      isFeatured: false
    },
    {
      id: 810,
      category: 'electronics',
      name: 'Philips Multi-Grooming All-in-One Trimmer Set',
      nameMl: 'ഫിലിപ്സ് ഷേവിംഗ് ട്രിമ്മർ സെറ്റ്',
      brand: 'Philips',
      weight: '9 in 1 Trimmer',
      price: 1699,
      oldPrice: 2195,
      discount: '23% OFF',
      image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 310,
      stock: 'In Stock',
      description: 'Self-sharpening stainless steel blades with 60 mins cordless runtime for beard, hair and body styling.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 811,
      category: 'electronics',
      name: 'Wonderchef Nutri-Blend 400W Mixer Smoothie Maker',
      nameMl: 'വണ്ടർചെഫ് ന്യൂട്രി-ബ്ലെൻഡ് 400W',
      brand: 'Wonderchef',
      weight: '2 Unbreakable Jars',
      price: 2499,
      oldPrice: 3800,
      discount: '34% OFF',
      image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 140,
      stock: 'In Stock',
      description: '22,000 RPM high speed motor extracting all micro-nutrients from fruits and vegetables instantly.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 812,
      category: 'electronics',
      name: 'Pigeon Stainless Steel 3-Tier Idli Cooker Stand',
      nameMl: 'പിജിയൻ ഇഡ്ഡലി കുക്കർ പാത്രം (12 ഇഡ്ഡലി)',
      brand: 'Pigeon',
      weight: '12 Idli Capacity',
      price: 599,
      oldPrice: 895,
      discount: '33% OFF',
      image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 110,
      stock: 'In Stock',
      description: 'Heavy gauge food grade stainless steel plates with steam vents for fluffy breakfast idlis.',
      isDeal: false,
      isFeatured: false
    },

    // ----------------- 10. FASHION & APPARELS (12 Items) -----------------
    {
      id: 901,
      category: 'fashion',
      name: 'Authentic Kerala Kasavu Double Mundu (Gold Border)',
      nameMl: 'സ്വർണ്ണക്കസവ് ഡബിൾ മുണ്ട്',
      brand: 'Kerala Weaves',
      weight: '4 Metres Pure Cotton',
      price: 499,
      oldPrice: 750,
      discount: '33% OFF',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 340,
      stock: 'In Stock',
      description: 'Handwoven pure cotton Kerala double mundu with rich zari gold border for festivals, temples and weddings.',
      isDeal: true,
      isFeatured: true
    },
    {
      id: 902,
      category: 'fashion',
      name: 'Kerala Traditional Set Mundu with Mural Print',
      nameMl: 'മ്യൂറൽ പ്രിന്റ് സെറ്റ് മുണ്ട്',
      brand: 'Travancore Silk',
      weight: 'Pure Cotton Set',
      price: 899,
      oldPrice: 1350,
      discount: '33% OFF',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 190,
      stock: 'In Stock',
      description: 'Elegant cream and gold cotton set mundu embellished with traditional peacock mural painting motifs.',
      isDeal: false,
      isFeatured: true
    },
    {
      id: 903,
      category: 'fashion',
      name: 'Mens 100% Pure Cotton Formal Shirt (White)',
      nameMl: 'പുരുഷന്മാരുടെ കോട്ടൺ വൈറ്റ് ഷർട്ട്',
      brand: 'Golden Weaves',
      weight: 'Size 40 / Medium',
      price: 549,
      oldPrice: 799,
      discount: '31% OFF',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 120,
      stock: 'In Stock',
      description: 'Breathable, crisp combed cotton fabric suited for tropical Kerala weather and formal occasions.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 904,
      category: 'fashion',
      name: 'Kerala Soft Cotton Bath Towel / Thorthu (Pack of 5)',
      nameMl: 'നാടൻ കോട്ടൺ തോർത്ത് (5 എണ്ണം)',
      brand: 'Pala Weaves',
      weight: 'Pack of 5 Towels',
      price: 199,
      oldPrice: 299,
      discount: '33% OFF',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 410,
      stock: 'In Stock',
      description: 'Classic quick-drying, ultra absorbent 100% cotton bath thorthu in assorted traditional border stripes.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 905,
      category: 'fashion',
      name: 'St. George 3-Fold Heavy Windproof Umbrella (Pala Special)',
      nameMl: '3-ഫോൾഡ് വിൻഡ്പ്രൂഫ് കുട',
      brand: 'St. George',
      weight: 'Black UV Coated',
      price: 349,
      oldPrice: 480,
      discount: '27% OFF',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 280,
      stock: 'In Stock',
      description: 'Built for heavy Kerala monsoons with reinforced fiberglass ribs and silver UV heat shield.',
      isDeal: true,
      isFeatured: false
    },
    {
      id: 906,
      category: 'fashion',
      name: 'Women Soft Cotton Floral Daily Kurti',
      nameMl: 'കോട്ടൺ ഡെയിലി കുർത്തി (L)',
      brand: 'Ananya Trends',
      weight: 'Size L / Pure Cotton',
      price: 499,
      oldPrice: 750,
      discount: '33% OFF',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 140,
      stock: 'In Stock',
      description: 'Straight fit daily wear kurti with side slits, breathable natural cotton fabric and fast colors.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 907,
      category: 'fashion',
      name: 'Kids Kerala Traditional Kasavu Pavada Set',
      nameMl: 'കുട്ടികളുടെ പട്ടുപാവാട സെറ്റ് (4-6 വയസ്സ്)',
      brand: 'Little Stars',
      weight: 'Age 4-6 Years',
      price: 649,
      oldPrice: 950,
      discount: '32% OFF',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
      rating: 4.9,
      reviews: 110,
      stock: 'In Stock',
      description: 'Adorable festive cream and gold pavada blouse set for Onam, Vishu and birthday celebrations.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 908,
      category: 'fashion',
      name: 'Bombay Dyeing 100% Cotton Double Bed Sheet with 2 Pillow Covers',
      nameMl: 'ബോംബെ ഡൈയിംഗ് ബെഡ്ഷീറ്റ് സെറ്റ്',
      brand: 'Bombay Dyeing',
      weight: 'Double King (220x240cm)',
      price: 799,
      oldPrice: 1200,
      discount: '33% OFF',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 165,
      stock: 'In Stock',
      description: '200 Thread count pure cotton floral bedsheet set with zero shrinkage and fade-resistant print.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 909,
      category: 'fashion',
      name: 'Mens Casual Linen Cotton Kurta (Pastel Green)',
      nameMl: 'ലിനൻ കോട്ടൺ കുർത്ത',
      brand: 'Golden Weaves',
      weight: 'Size 42 / Large',
      price: 699,
      oldPrice: 999,
      discount: '30% OFF',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 85,
      stock: 'In Stock',
      description: 'Mandarin collar stylish casual kurta in soothing pastel green for festive and family gatherings.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 910,
      category: 'fashion',
      name: 'Paragon Mens Waterproof Daily Slippers',
      nameMl: 'പാരഗൺ പുരുഷന്മാരുടെ സ്ലിപ്പർ',
      brand: 'Paragon',
      weight: 'Size 8 UK',
      price: 249,
      oldPrice: 299,
      discount: '17% OFF',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 310,
      stock: 'In Stock',
      description: 'Durable anti-skid rubber sole slippers for comfortable home and outdoor daily wear.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 911,
      category: 'fashion',
      name: 'Microfiber Super Soft Fluffy Bath Robe (Unisex)',
      nameMl: 'മൈക്രോഫൈബർ ബാത്ത് റോബ്',
      brand: 'Home Comfort',
      weight: 'Free Size',
      price: 649,
      oldPrice: 990,
      discount: '34% OFF',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
      rating: 4.7,
      reviews: 65,
      stock: 'In Stock',
      description: 'Ultra absorbent, plush microfiber robe with waist belt and two front deep pockets.',
      isDeal: false,
      isFeatured: false
    },
    {
      id: 912,
      category: 'fashion',
      name: 'Kids Cotton Summer Shorts & T-Shirt Combo Set',
      nameMl: 'കുട്ടികളുടെ ടി-ഷർട്ട് & ഷോർട്സ് സെറ്റ്',
      brand: 'Little Stars',
      weight: 'Age 5-7 Years',
      price: 399,
      oldPrice: 599,
      discount: '33% OFF',
      image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
      rating: 4.8,
      reviews: 130,
      stock: 'In Stock',
      description: 'Soft combed 100% cotton casual set with playful cartoon prints and elasticated waist.',
      isDeal: false,
      isFeatured: false
    }
  ],

  // Helper utility methods
  getCategoryById(id) {
    if (!id) return null;
    return this.categories.find(c => c.id.toLowerCase() === id.toLowerCase()) || null;
  },

  getProductById(id) {
    const numId = parseInt(id, 10);
    return this.products.find(p => p.id === numId);
  },

  getProductsByCategory(catId) {
    if (!catId || catId === 'all') return this.products;
    return this.products.filter(p => p.category === catId);
  },

  getFeaturedDeals() {
    return this.products.filter(p => p.isDeal);
  },

  searchProducts(query, category = 'all') {
    const q = (query || '').toLowerCase().trim();
    return this.products.filter(p => {
      const matchCat = (category === 'all' || p.category === category);
      const matchText = !q || p.name.toLowerCase().includes(q) || 
                              p.nameMl.includes(q) || 
                              p.brand.toLowerCase().includes(q) || 
                              p.description.toLowerCase().includes(q);
      return matchCat && matchText;
    });
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = siteData;
}
